### ISSUE TITLE
Polybar

### ISSUE THREAD

**Issue by LexaproDelirium** [juminai/bspdots#1]
Hey men! i loved your polybar config. Whenever i try to use your config it keeps giving me error. This might can be me problem, im not sure but can you check the polybar config and make sure its ok. Like i said its prob me problem since im kinda noob and I have to say it again, your polybar looks so gorgeous.

Uncaught exception, shuting down: The config file contains multiple bars, but no bar name was given. Available bars: base, memory, pulseaudio, rofi, spotify, time, weather.

**Comment by juminai** [comment]
How are you starting polybar?

**Comment by LexaproDelirium** [comment]
tried starting with the .sh and rofi and terminal. Im pretty sure im doing something wrong ://
