### ISSUE TITLE
List of apps and folder structures

### ISSUE THREAD

**Issue by rishavnandi** [juminai/bspdots#3]
Hey man, awesome work with the dotfiles, I just wanted to know all the dependencies and apps that you are using that are required for these dots just to make sure I'm not missing anything and it'd be really helpful if you could tell me the folder structure since I'm new to wm's and my configs are structured slightly differently...

Thanks again!

**Comment by juminai** [comment]
bin folder -> ~/.local
all files in config folder -> ~/.config
all files in misc/home -> ~

fonts needed: Roboto, Roboto Mono, Iosevka Nerd Font, SF Pro, Font Awesome 6 Pro

**Comment by rishavnandi** [comment]
Thanks man! I was wondering what all fonts you were using I figured out most of them through the configs but wanted to make sure..

Also you're using pulseaudio right?

**Comment by juminai** [comment]
If you use arch linux, the packages are pulseaudio pulseaudio-alsa alsa-utils
